title: Coders.Bay Diareey
author: Nerdbert
email: norbert_fruehwirth@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Diareey for Coders.Bay to check what we have done until now and what they "lessons learned" are!!

# social links
linked_in: https://bit.ly/3zBunSK
github_username:  kodibert

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
